name: publish

on: [push, pull_request]

env:
  DOTNET_SDK_VERSION: 8.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Pack
        run: dotnet pack DotaCrypto -c Release -o "out" -p:ContinuousIntegrationBuild=true --nologo

      - name: Rename artifacts
        shell: sh
        run: |
          set -eu

          mv out/ezhevita.DotaCrypto.*.nupkg "out/ezhevita.DotaCrypto.nupkg"
          mv out/ezhevita.DotaCrypto.*.snupkg "out/ezhevita.DotaCrypto.snupkg"

      - name: Upload nupkg
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ezhevita.DotaCrypto.nupkg
          path: out/ezhevita.DotaCrypto.nupkg

      - name: Upload snupkg
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ezhevita.DotaCrypto.snupkg
          path: out/ezhevita.DotaCrypto.snupkg

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Download nupkg artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ezhevita.DotaCrypto.nupkg
          path: out

      - name: Download snupkg artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ezhevita.DotaCrypto.snupkg
          path: out

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "out/*"
          makeLatest: true
          name: DotaCrypto V${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create NuGet release
        run: dotnet nuget push "out/ezhevita.DotaCrypto.nupkg" -k "${{ secrets.NUGET_PUBLISH_API_KEY }}" -s "https://api.nuget.org/v3/index.json"
